  services:

    backend:
      image : go-backend:latest
      depends_on:
        - moori-database
        - meilisearch
        - qdrant
#        - embedSvc
      ports:
        - "8088:8088"
      container_name: go-backend-app
      restart: always
      build:
        dockerfile: Dockerfile
        context: .
#    embedSvc:
#      image: embed-svc:latest
#      ports:
#        - "50051:50051"
#      container_name: embedSvc-app
#      restart: always
#      build:
#        dockerfile: Dockerfile
#        context: ./embedSvc

    front-end:
      image: front-end:latest
      ports:
        - "3000:3000"
      container_name: front-end
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./front-end

    moori-database:
      image: mysql:8.0
      ports:
        - "3308:3306"
      container_name: moori-database
      volumes:
        - dbdata:/var/lib/mysql
      restart: always
      command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
      environment:
        MYSQL_ROOT_PASSWORD: mooriappRoo7t0lk2o20
        MYSQL_DATABASE: moori_db
        MYSQL_USER: mooriapp
        MYSQL_PASSWORD: mooriappt0lk2o20

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      depends_on:
        - moori-database
      environment:
        PMA_HOST: moori-database
        MYSQL_ROOT_PASSWORD: mooriappRoo7t0lk2o20
      ports:
        - "8080:80"


    meilisearch:
      image: getmeili/meilisearch:v1.11
      container_name: meilisearch
      ports:
        - "7700:7700"
      environment:
        - MEILI_ENV=development
#        - MEILI_MASTER_KEY="MASTER_KEY"
      volumes:
        - ./meili_data:/meili_data
      restart: always


    qdrant:
      image: qdrant/qdrant
      container_name: qdrant
      ports:
        - "6333:6333"
        - "6334:6334"
      volumes:
        - ./qdrant_storage:/qdrant/storage:z
      restart: unless-stopped

  volumes:
    dbdata:
