# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedder.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'embedder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mbedder.proto\x12\x08\x65mbedder\"$\n\x13TextToVectorRequest\x12\r\n\x05query\x18\x01 \x01(\t\"#\n\x11TextToVectorReply\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"\'\n\x12ImageVectorRequest\x12\x11\n\timage_url\x18\x01 \x03(\t\"5\n\x10ImageVectorReply\x12!\n\x07vectors\x18\x01 \x03(\x0b\x32\x10.embedder.Vector\"\x18\n\x06Vector\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32\xad\x01\n\x08\x45mbedder\x12P\n\x10ReturnTextVector\x12\x1d.embedder.TextToVectorRequest\x1a\x1b.embedder.TextToVectorReply\"\x00\x12O\n\x11ReturnImageVector\x12\x1c.embedder.ImageVectorRequest\x1a\x1a.embedder.ImageVectorReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTTOVECTORREQUEST']._serialized_start=28
  _globals['_TEXTTOVECTORREQUEST']._serialized_end=64
  _globals['_TEXTTOVECTORREPLY']._serialized_start=66
  _globals['_TEXTTOVECTORREPLY']._serialized_end=101
  _globals['_IMAGEVECTORREQUEST']._serialized_start=103
  _globals['_IMAGEVECTORREQUEST']._serialized_end=142
  _globals['_IMAGEVECTORREPLY']._serialized_start=144
  _globals['_IMAGEVECTORREPLY']._serialized_end=197
  _globals['_VECTOR']._serialized_start=199
  _globals['_VECTOR']._serialized_end=223
  _globals['_EMBEDDER']._serialized_start=226
  _globals['_EMBEDDER']._serialized_end=399
# @@protoc_insertion_point(module_scope)
